"use client";

import { useEffect, useState } from "react";
import { IconEdit, IconPlus, IconTrash } from "@/components/icons";
import { Alert } from "@/components/ui/empty-state";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Field, SelectInput, TextInput } from "@/components/ui/field";
import { Modal } from "@/components/ui/modal";
import { PageHeader } from "@/components/ui/page-header";

type Company = { id: number; name: string };
type Rule = { field: string; operator: string; value: string };
type Segment = { id: number; company_id: number; name: string; description: string | null; rules: Rule[]; updated_at: string };
const emptyRule: Rule = { field: "status", operator: "equals", value: "active" };

export default function CrmSegmentsPage() {
  const [companies, setCompanies] = useState<Company[]>([]); const [segments, setSegments] = useState<Segment[]>([]); const [companyId, setCompanyId] = useState(""); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [rules, setRules] = useState<Rule[]>([emptyRule]); const [editingId, setEditingId] = useState<number | null>(null); const [open, setOpen] = useState(false); const [message, setMessage] = useState<{ text: string; tone: "success" | "danger" } | null>(null); const [saving, setSaving] = useState(false);
  async function loadCompanies() { const response = await fetch("/api/crm/companies", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Could not load companies."); setCompanies(result.companies ?? []); if (!companyId && result.companies?.length) setCompanyId(String(result.companies[0].id)); }
  async function loadSegments() { if (!companyId) return; const response = await fetch(`/api/crm/segments?company_id=${companyId}`, { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Could not load segments."); setSegments(result.segments ?? []); }
  useEffect(() => { loadCompanies().catch((error) => setMessage({ text: error.message, tone: "danger" })); }, []); useEffect(() => { loadSegments().catch((error) => setMessage({ text: error.message, tone: "danger" })); }, [companyId]);
  function reset() { setEditingId(null); setName(""); setDescription(""); setRules([{ ...emptyRule }]); }
  function edit(segment: Segment) { setEditingId(segment.id); setName(segment.name); setDescription(segment.description ?? ""); setRules(segment.rules?.length ? segment.rules : [{ ...emptyRule }]); setOpen(true); }
  function addRule() { if (rules.length < 10) setRules([...rules, { field: "email", operator: "contains", value: "" }]); }
  async function save() { setSaving(true); try { const response = await fetch("/api/crm/segments", { method: editingId ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: editingId ?? undefined, company_id: Number(companyId), name, description, rules }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Could not save segment."); setOpen(false); setMessage({ text: editingId ? "Segment updated." : "Segment created.", tone: "success" }); await loadSegments(); } catch (error) { setMessage({ text: error instanceof Error ? error.message : "Could not save segment.", tone: "danger" }); } finally { setSaving(false); } }
  async function remove(segment: Segment) { if (!window.confirm(`Delete ${segment.name}?`)) return; const response = await fetch(`/api/crm/segments?id=${segment.id}`, { method: "DELETE" }); const result = await response.json(); if (!response.ok) { setMessage({ text: result.error ?? "Could not delete segment.", tone: "danger" }); return; } setMessage({ text: "Segment deleted.", tone: "success" }); await loadSegments(); }
  return <>
    <PageHeader eyebrow="Business CRM / Audiences" title="Segments" description="Build reusable company audiences from clear contact rules, then use them in campaigns." actions={<Button onClick={() => { reset(); setOpen(true); }} disabled={!companyId}><IconPlus className="h-4 w-4" />New segment</Button>} />
    {message ? <div className="mb-5"><Alert tone={message.tone}>{message.text}</Alert></div> : null}
    <Card className="mb-5"><Field label="Company"><SelectInput value={companyId} onChange={(event) => setCompanyId(event.target.value)}>{companies.map((company) => <option key={company.id} value={company.id}>{company.name}</option>)}</SelectInput></Field></Card>
    {segments.length ? <div className="grid gap-4 xl:grid-cols-2">{segments.map((segment) => <Card key={segment.id}><div className="flex items-start justify-between gap-4"><div><Badge tone="primary">{segment.rules.length} rule{segment.rules.length === 1 ? "" : "s"}</Badge><h2 className="mt-3 text-lg font-bold">{segment.name}</h2><p className="mt-1 text-sm text-muted">{segment.description || "No description"}</p></div><div className="flex gap-1"><button className="grid h-8 w-8 place-items-center rounded-lg text-muted hover:bg-primary-soft hover:text-primary" onClick={() => edit(segment)} aria-label={`Edit ${segment.name}`}><IconEdit className="h-4 w-4" /></button><button className="grid h-8 w-8 place-items-center rounded-lg text-muted hover:bg-rose-50 hover:text-rose-600" onClick={() => remove(segment)} aria-label={`Delete ${segment.name}`}><IconTrash className="h-4 w-4" /></button></div></div><div className="mt-4 space-y-2">{segment.rules.map((rule, index) => <div key={`${rule.field}-${index}`} className="rounded-lg bg-[#fcfaf9] px-3 py-2 text-xs font-medium text-muted"><span className="font-bold text-foreground">{rule.field}</span> {rule.operator.replaceAll("_", " ")} <span className="font-bold text-primary">{rule.value}</span></div>)}</div></Card>)}</div> : <Card><div className="py-12 text-center"><p className="text-lg font-bold">No segments yet</p><p className="mt-2 text-sm text-muted">Create a reusable audience for your next campaign.</p><Button className="mt-5" onClick={() => { reset(); setOpen(true); }}><IconPlus className="h-4 w-4" />Create segment</Button></div></Card>}
    <Modal open={open} onClose={() => setOpen(false)} title={editingId ? "Edit segment" : "Create segment"} description="Rules are combined with AND. Supported fields are core contact fields only; no arbitrary SQL is accepted."><div className="space-y-5"><Field label="Segment name"><TextInput value={name} onChange={(event) => setName(event.target.value)} placeholder="Active customers" /></Field><Field label="Description"><TextInput value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Contacts ready for the next campaign" /></Field><div><div className="mb-2 flex items-center justify-between"><p className="text-sm font-semibold">Rules</p><button className="text-xs font-bold text-primary" onClick={addRule} disabled={rules.length >= 10}>+ Add rule</button></div><div className="space-y-3">{rules.map((rule, index) => <div key={index} className="grid gap-2 rounded-xl border border-border p-3 sm:grid-cols-[1fr_1fr_1.2fr_auto]"><SelectInput value={rule.field} onChange={(event) => setRules(rules.map((item, itemIndex) => itemIndex === index ? { ...item, field: event.target.value } : item))}><option value="first_name">First name</option><option value="last_name">Last name</option><option value="email">Email</option><option value="status">Status</option><option value="source">Source</option></SelectInput><SelectInput value={rule.operator} onChange={(event) => setRules(rules.map((item, itemIndex) => itemIndex === index ? { ...item, operator: event.target.value } : item))}><option value="equals">Equals</option><option value="not_equals">Not equals</option><option value="contains">Contains</option><option value="starts_with">Starts with</option></SelectInput><TextInput value={rule.value} onChange={(event) => setRules(rules.map((item, itemIndex) => itemIndex === index ? { ...item, value: event.target.value } : item))} placeholder="Value" />{rules.length > 1 ? <button className="text-xs font-bold text-rose-600" onClick={() => setRules(rules.filter((_, itemIndex) => itemIndex !== index))}>Remove</button> : <span />}</div>)}</div></div><div className="flex justify-end gap-2 border-t border-border pt-4"><Button variant="secondary" onClick={() => setOpen(false)}>Cancel</Button><Button loading={saving} onClick={save}>Save segment</Button></div></div></Modal>
  </>;
}
