"use client";

import Link from "next/link";
import { useEffect, useState, type FormEvent } from "react";
import { IconArrowRight } from "@/components/icons";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Alert, EmptyState } from "@/components/ui/empty-state";
import { TextInput } from "@/components/ui/field";

 type Order = {
  id: number; public_order_id: string; lead_id: number; service_name: string;
  service_charges?: string | null; service_deadline: string; is_writing: boolean;
  word_count?: number | null; subject_area?: string | null; status: string;
  created_at: string; completed_at?: string | null;
  crm_leads?: { id: number; name: string; email: string; phone?: string | null; crm_companies?: { name: string } | null; crm_websites?: { name: string } | null } | null;
  crm_experts?: { name: string; email?: string | null; service_area?: string | null } | null;
 };
 type Note = { id: number; note: string; created_at: string; author_name?: string };
 type Event = { id: number; event_type: string; created_at: string };

 function date(value?: string | null) { return value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Not set"; }
 function statusTone(value: string): "success" | "warning" | "danger" | "neutral" { return value === "completed" ? "success" : value === "cancelled" ? "danger" : value === "pending" ? "warning" : "neutral"; }
 const statuses = ["pending", "in_progress", "completed", "cancelled"];

 export default function OrderDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const [id, setId] = useState(""); const [order, setOrder] = useState<Order | null>(null); const [notes, setNotes] = useState<Note[]>([]); const [events, setEvents] = useState<Event[]>([]); const [note, setNote] = useState(""); const [message, setMessage] = useState<{ text: string; tone?: "success" | "danger" } | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  async function load(orderId: string) { const response = await fetch(`/api/crm/orders/${orderId}`, { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Could not load order."); setOrder(result.order); setNotes(result.notes ?? []); setEvents(result.events ?? []); setLoading(false); }
  useEffect(() => { params.then((value) => { setId(value.id); load(value.id).catch((error) => { setMessage({ text: error.message, tone: "danger" }); setLoading(false); }); }); }, [params]);
  async function updateStatus(status: string) { if (!order || status === order.status) return; setSaving(true); const response = await fetch(`/api/crm/orders/${order.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); const result = await response.json(); if (!response.ok) setMessage({ text: result.error ?? "Could not update order status.", tone: "danger" }); else { setMessage({ text: "Order status updated.", tone: "success" }); await load(id); } setSaving(false); }
  async function addNote(event: FormEvent) { event.preventDefault(); if (!note.trim()) return; const response = await fetch(`/api/crm/orders/${id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "note", note }) }); const result = await response.json(); if (!response.ok) setMessage({ text: result.error ?? "Could not add note.", tone: "danger" }); else { setNote(""); await load(id); } }
  if (loading) return <div className="p-8"><EmptyState text="Loading order workspace..." /></div>;
  if (!order) return <div className="p-8"><Alert tone="danger">Order not found.</Alert></div>;
  const progressIndex = statuses.indexOf(order.status);
  return <div className="mx-auto max-w-[1500px]">
    <div className="mb-5 flex items-center gap-2 text-xs font-semibold text-muted"><Link href="/dashboard/crm/orders" className="hover:text-primary">Orders</Link><span>/</span><span className="text-foreground">Work order #{order.public_order_id}</span></div>
    {message ? <div className="mb-5"><Alert tone={message.tone}>{message.text}</Alert></div> : null}
    <section className="mb-5 overflow-hidden rounded-2xl border border-border bg-white shadow-[0_8px_28px_rgba(28,20,18,0.04)]">
      <div className="flex flex-col gap-5 border-b border-border px-6 py-6 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-primary">Work order #{order.public_order_id}</p><h1 className="mt-2 max-w-3xl text-3xl font-bold tracking-tight text-foreground">{order.service_name}</h1><p className="mt-2 text-sm text-muted">Assigned to {order.crm_experts?.name || "an expert"} · created {date(order.created_at)}</p></div><div className="flex flex-wrap gap-2"><Link href={`/dashboard/crm/leads/${order.lead_id}`} className="inline-flex items-center gap-2 rounded-lg border border-border bg-white px-3 py-2 text-sm font-semibold text-muted hover:border-primary/30 hover:text-primary">Client profile<IconArrowRight className="h-4 w-4" /></Link>{order.status !== "completed" && order.status !== "cancelled" ? <Button onClick={() => updateStatus("completed")} loading={saving}>Complete work</Button> : null}</div></div>
      <div className="grid grid-cols-2 divide-x divide-y divide-border lg:grid-cols-4 lg:divide-y-0"><div className="px-6 py-4"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-stone-400">Current status</p><div className="mt-2"><Badge tone={statusTone(order.status)}>{order.status.replace("_", " ")}</Badge></div></div><div className="px-6 py-4"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-stone-400">Deadline</p><p className="mt-2 truncate text-sm font-semibold">{date(order.service_deadline)}</p></div><div className="px-6 py-4"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-stone-400">Charges</p><p className="mt-2 text-sm font-semibold">{order.service_charges ? `PKR ${order.service_charges}` : "Not set"}</p></div><div className="px-6 py-4"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-stone-400">Completed</p><p className="mt-2 truncate text-sm font-semibold">{order.completed_at ? date(order.completed_at) : "Not completed"}</p></div></div>
    </section>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_340px]">
      <main className="min-w-0 space-y-5">
        <section className="rounded-2xl border border-border bg-white p-5 shadow-[0_8px_28px_rgba(28,20,18,0.03)]"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Work progress</h2><p className="mt-1 text-xs text-muted">Move the order through its delivery lifecycle.</p></div><Badge tone={statusTone(order.status)}>{order.status.replace("_", " ")}</Badge></div><div className="mt-5 grid gap-2 sm:grid-cols-4">{statuses.map((status, index) => <button key={status} type="button" disabled={saving || status === order.status} onClick={() => updateStatus(status)} className={`rounded-xl border px-3 py-3 text-left transition ${status === order.status ? "border-primary bg-primary-soft ring-2 ring-primary/10" : index < progressIndex && order.status !== "cancelled" ? "border-emerald-200 bg-emerald-50/60" : "border-border bg-[#fcfaf9] hover:border-primary/30"}`}><span className={`mb-2 block h-1.5 w-8 rounded-full ${status === order.status ? "bg-primary" : index < progressIndex ? "bg-emerald-500" : "bg-stone-200"}`} /><span className="block text-sm font-semibold capitalize">{status.replace("_", " ")}</span></button>)}</div></section>
        <section className="rounded-2xl border border-border bg-white shadow-[0_8px_28px_rgba(28,20,18,0.03)]"><div className="border-b border-border px-5 py-4"><h2 className="font-semibold">Service brief</h2><p className="mt-1 text-xs text-muted">The delivery requirements attached to this work order.</p></div><div className="grid gap-3 bg-[#fcfaf9] p-4 sm:grid-cols-3"><div className="rounded-xl border border-sky-200 bg-sky-50/70 px-4 py-3"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-sky-700">Service</p><p className="mt-1.5 text-sm font-semibold">{order.service_name}</p></div><div className="rounded-xl border border-violet-200 bg-violet-50/70 px-4 py-3"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-violet-700">Writing order</p><p className="mt-1.5 text-sm font-semibold">{order.is_writing ? "Yes" : "No"}</p></div><div className="rounded-xl border border-amber-200 bg-amber-50/70 px-4 py-3"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-amber-700">Word count / subject</p><p className="mt-1.5 text-sm font-semibold">{order.word_count ?? "Not set"} · {order.subject_area || "Not set"}</p></div></div></section>
        <section className="rounded-2xl border border-border bg-white p-5 shadow-[0_8px_28px_rgba(28,20,18,0.03)]"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Activity log</h2><p className="mt-1 text-xs text-muted">A chronological record of work on this order.</p></div><span className="text-xs text-muted">{events.length} events</span></div><div className="mt-5 space-y-4">{events.map((event) => <div key={event.id} className="flex gap-3"><span className="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-primary" /><div><p className="text-sm capitalize">{event.event_type.replaceAll("_", " ")}</p><p className="mt-0.5 text-xs text-muted">{date(event.created_at)}</p></div></div>)}{!events.length ? <p className="text-sm text-muted">No activity recorded yet.</p> : null}</div></section>
      </main>
      <aside className="space-y-5"><section className="rounded-2xl border border-border bg-white p-5 shadow-[0_8px_28px_rgba(28,20,18,0.03)]"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-stone-400">Assigned specialist</p><h2 className="mt-2 text-xl font-bold">{order.crm_experts?.name || "Not assigned"}</h2><p className="mt-1 text-sm text-muted">{order.crm_experts?.email || "No email"}</p><span className="mt-3 inline-flex rounded-full bg-primary-soft px-2.5 py-1 text-xs font-semibold text-primary">{order.crm_experts?.service_area || "No service area"}</span></section><section className="rounded-2xl border border-border bg-white p-5 shadow-[0_8px_28px_rgba(28,20,18,0.03)]"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-stone-400">Client reference</p><h2 className="mt-2 text-lg font-bold">{order.crm_leads?.name || "Unknown client"}</h2><p className="mt-1 text-sm text-muted">{order.crm_leads?.email || "No email"}</p><p className="mt-3 text-xs text-muted">{order.crm_leads?.crm_companies?.name || "Company not provided"} · {order.crm_leads?.crm_websites?.name || "Website not provided"}</p><Link href={`/dashboard/crm/leads/${order.lead_id}`} className="mt-4 block text-sm font-semibold text-primary hover:underline">Open client profile</Link></section><section className="rounded-2xl border border-border bg-white p-5 shadow-[0_8px_28px_rgba(28,20,18,0.03)]"><div className="flex items-center justify-between"><h2 className="font-semibold">Work notes</h2><span className="text-xs text-muted">{notes.length}</span></div><div className="mt-4 max-h-64 space-y-3 overflow-y-auto">{notes.map((item) => <div key={item.id} className="rounded-xl border border-border bg-[#fcfaf9] p-3"><p className="text-sm leading-6">{item.note}</p><p className="mt-1 text-[11px] text-muted">{item.author_name || "Author not recorded"} · {date(item.created_at)}</p></div>)}{!notes.length ? <p className="text-sm text-muted">No work notes yet.</p> : null}</div><form className="mt-4 flex flex-col gap-2 sm:flex-row" onSubmit={addNote}><TextInput className="min-w-0 flex-1" value={note} onChange={(event) => setNote(event.target.value)} placeholder="Write an order note..." /><Button type="submit">Add note</Button></form></section></aside>
    </div>
  </div>;
 }
