-- Digify CRM foundation migration.
-- Run after the existing device, employee, and attendance migrations.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.profiles (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role VARCHAR(30) NOT NULL DEFAULT 'employee' CHECK (role IN ('superadmin', 'employee')),
  employee_id BIGINT UNIQUE REFERENCES public.employees(id) ON DELETE SET NULL,
  full_name VARCHAR(255),
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.shift_timings (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  grace_minutes INT NOT NULL DEFAULT 15 CHECK (grace_minutes >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.departments (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.positions (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS auth_user_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS employee_number BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS department_id BIGINT;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS position_id BIGINT;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS shift_id BIGINT;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS physical_address TEXT;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS cnic VARCHAR(30);
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS joining_date DATE;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'active';

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'employees_department_id_fkey') THEN
    ALTER TABLE public.employees ADD CONSTRAINT employees_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id) ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'employees_position_id_fkey') THEN
    ALTER TABLE public.employees ADD CONSTRAINT employees_position_id_fkey FOREIGN KEY (position_id) REFERENCES public.positions(id) ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'employees_shift_id_fkey') THEN
    ALTER TABLE public.employees ADD CONSTRAINT employees_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES public.shift_timings(id) ON DELETE SET NULL;
  END IF;
END
$$;

ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS arrival_status VARCHAR(30);
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS day_status VARCHAR(30);
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS hours_worked NUMERIC(6,2);
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS session_start TIMESTAMPTZ;
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS session_end TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS public.leaves (
  id BIGSERIAL PRIMARY KEY,
  employee_id BIGINT NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  reason TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'declined')),
  reviewed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (end_date >= start_date)
);

CREATE TABLE IF NOT EXISTS public.salaries (
  id BIGSERIAL PRIMARY KEY,
  employee_id BIGINT NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  month DATE NOT NULL,
  base_salary NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (base_salary >= 0),
  late_days INT NOT NULL DEFAULT 0 CHECK (late_days >= 0),
  absent_days INT NOT NULL DEFAULT 0 CHECK (absent_days >= 0),
  half_days INT NOT NULL DEFAULT 0 CHECK (half_days >= 0),
  late_deduction_enabled BOOLEAN NOT NULL DEFAULT true,
  deduction_amount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (deduction_amount >= 0),
  net_pay NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (net_pay >= 0),
  status VARCHAR(20) NOT NULL DEFAULT 'unpaid' CHECK (status IN ('unpaid', 'paid')),
  paid_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (employee_id, month)
);

CREATE TABLE IF NOT EXISTS public.salary_deduction_rules (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  attendance_status VARCHAR(30) NOT NULL CHECK (attendance_status IN ('late', 'half_day', 'absent')),
  qualifying_days INT NOT NULL CHECK (qualifying_days > 0),
  deduction_days NUMERIC(6,2) NOT NULL CHECK (deduction_days > 0),
  is_enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.companies (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(150) NOT NULL UNIQUE,
  logo_url TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.company_accounts (
  id BIGSERIAL PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  platform_name VARCHAR(100) NOT NULL,
  login VARCHAR(255) NOT NULL,
  encrypted_password BYTEA NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.expenses (
  id BIGSERIAL PRIMARY KEY,
  source VARCHAR(20) NOT NULL DEFAULT 'manual' CHECK (source IN ('manual', 'salary')),
  salary_id BIGINT UNIQUE REFERENCES public.salaries(id) ON DELETE SET NULL,
  amount NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
  description TEXT NOT NULL,
  expense_date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.revenues (
  id BIGSERIAL PRIMARY KEY,
  amount NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
  description TEXT NOT NULL,
  revenue_date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.permissions (
  id BIGSERIAL PRIMARY KEY,
  employee_id BIGINT NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  module VARCHAR(80) NOT NULL,
  can_read BOOLEAN NOT NULL DEFAULT false,
  can_add BOOLEAN NOT NULL DEFAULT false,
  can_edit BOOLEAN NOT NULL DEFAULT false,
  can_delete BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (employee_id, module)
);

CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGSERIAL PRIMARY KEY,
  recipient_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  type VARCHAR(50) NOT NULL,
  message TEXT NOT NULL,
  is_read BOOLEAN NOT NULL DEFAULT false,
  related_record_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_employees_auth_user_id ON public.employees(auth_user_id);
CREATE INDEX IF NOT EXISTS idx_employees_status ON public.employees(status);
CREATE INDEX IF NOT EXISTS idx_employees_shift_id ON public.employees(shift_id);
CREATE INDEX IF NOT EXISTS idx_leaves_employee_dates ON public.leaves(employee_id, start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_salaries_month ON public.salaries(month);
CREATE INDEX IF NOT EXISTS idx_company_accounts_company_id ON public.company_accounts(company_id);
CREATE INDEX IF NOT EXISTS idx_expenses_date ON public.expenses(expense_date);
CREATE INDEX IF NOT EXISTS idx_revenues_date ON public.revenues(revenue_date);
CREATE INDEX IF NOT EXISTS idx_notifications_recipient ON public.notifications(recipient_id, is_read);

CREATE OR REPLACE FUNCTION public.is_superadmin()
RETURNS BOOLEAN
LANGUAGE SQL
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE user_id = auth.uid() AND role = 'superadmin' AND is_active = true
  );
$$;

REVOKE ALL ON FUNCTION public.is_superadmin() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_superadmin() TO anon, authenticated;

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shift_timings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.positions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leaves ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.salaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.salary_deduction_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.revenues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- The old migrations exposed these tables publicly. Remove those policies before
-- replacing them with authenticated role-aware policies.
DROP POLICY IF EXISTS devices_select_policy ON public.devices;
DROP POLICY IF EXISTS devices_insert_policy ON public.devices;
DROP POLICY IF EXISTS devices_all_policy ON public.devices;
DROP POLICY IF EXISTS employees_select_policy ON public.employees;
DROP POLICY IF EXISTS employees_insert_policy ON public.employees;
DROP POLICY IF EXISTS employees_all_policy ON public.employees;
DROP POLICY IF EXISTS attendance_all_policy ON public.attendance;
DROP POLICY IF EXISTS zkteco_sync_logs_all_policy ON public.zkteco_sync_logs;

CREATE POLICY profiles_self_or_admin ON public.profiles FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.is_superadmin());
CREATE POLICY profiles_admin_write ON public.profiles FOR ALL TO authenticated USING (public.is_superadmin()) WITH CHECK (public.is_superadmin());

CREATE POLICY devices_authenticated_access ON public.devices FOR ALL TO authenticated USING (public.is_superadmin()) WITH CHECK (public.is_superadmin());
CREATE POLICY employees_admin_access ON public.employees FOR ALL TO authenticated USING (public.is_superadmin()) WITH CHECK (public.is_superadmin());
CREATE POLICY employees_self_read ON public.employees FOR SELECT TO authenticated USING (auth_user_id = auth.uid());
CREATE POLICY attendance_admin_access ON public.attendance FOR ALL TO authenticated USING (public.is_superadmin()) WITH CHECK (public.is_superadmin());
CREATE POLICY attendance_self_read ON public.attendance FOR SELECT TO authenticated USING (employee_id IN (SELECT employee_id FROM public.profiles WHERE user_id = auth.uid()));
CREATE POLICY sync_logs_admin_access ON public.zkteco_sync_logs FOR ALL TO authenticated USING (public.is_superadmin()) WITH CHECK (public.is_superadmin());

CREATE POLICY shifts_admin_access ON public.shift_timings FOR ALL TO authenticated USING (public.is_superadmin()) WITH CHECK (public.is_superadmin());
CREATE POLICY departments_admin_access ON public.departments FOR ALL TO authenticated USING (public.is_superadmin()) WITH CHECK (public.is_superadmin());
CREATE POLICY positions_admin_access ON public.positions FOR ALL TO authenticated USING (public.is_superadmin()) WITH CHECK (public.is_superadmin());

CREATE POLICY leaves_admin_access ON public.leaves FOR ALL TO authenticated USING (public.is_superadmin()) WITH CHECK (public.is_superadmin());
CREATE POLICY leaves_employee_access ON public.leaves FOR SELECT TO authenticated USING (employee_id IN (SELECT employee_id FROM public.profiles WHERE user_id = auth.uid()));
CREATE POLICY leaves_employee_insert ON public.leaves FOR INSERT TO authenticated WITH CHECK (employee_id IN (SELECT employee_id FROM public.profiles WHERE user_id = auth.uid()));

CREATE POLICY salaries_admin_access ON public.salaries FOR ALL TO authenticated USING (public.is_superadmin()) WITH CHECK (public.is_superadmin());
CREATE POLICY salaries_employee_read ON public.salaries FOR SELECT TO authenticated USING (employee_id IN (SELECT employee_id FROM public.profiles WHERE user_id = auth.uid()));
CREATE POLICY salary_rules_admin_access ON public.salary_deduction_rules FOR ALL TO authenticated USING (public.is_superadmin()) WITH CHECK (public.is_superadmin());
CREATE POLICY companies_admin_access ON public.companies FOR ALL TO authenticated USING (public.is_superadmin()) WITH CHECK (public.is_superadmin());
CREATE POLICY company_accounts_admin_access ON public.company_accounts FOR ALL TO authenticated USING (public.is_superadmin()) WITH CHECK (public.is_superadmin());
CREATE POLICY expenses_admin_access ON public.expenses FOR ALL TO authenticated USING (public.is_superadmin()) WITH CHECK (public.is_superadmin());
CREATE POLICY revenues_admin_access ON public.revenues FOR ALL TO authenticated USING (public.is_superadmin()) WITH CHECK (public.is_superadmin());
CREATE POLICY permissions_admin_access ON public.permissions FOR ALL TO authenticated USING (public.is_superadmin()) WITH CHECK (public.is_superadmin());
CREATE POLICY notifications_recipient_read ON public.notifications FOR SELECT TO authenticated USING (recipient_id = auth.uid() OR public.is_superadmin());
CREATE POLICY notifications_admin_write ON public.notifications FOR ALL TO authenticated USING (public.is_superadmin()) WITH CHECK (public.is_superadmin());